site_name: MeshExpert Live!
site_description: A Mixed-Reality Show Product
site_author: Jianjun Xie

repo_url: https://github.com/jieseattle/datameshdocs

pages:
- Home: index.md
- Getting Started: getting-started.md